"""
Django settings for smart_bank project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
import environ

# -------------------------------------
# Base directory and environment setup
# -------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# -------------------------------------
# Security
# -------------------------------------
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-9ea#&0i&o5gxj1wno%*xer+sxweos!h%7*iyf5l4f9@l59e-8!"
)

# ✅ DEBUG = False on Render, True locally
DEBUG = env.bool("DEBUG", default=False)

# ✅ Allow localhost + Render domain
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "modulo-bank.onrender.com"]
)

# -------------------------------------
# Application definition
# -------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",

    # Local apps
    "apps.users",
    "apps.accounts",
    "apps.transactions",
    "apps.loans",
    "apps.fraud",
    "apps.audit",
    "apps.notifications",
    "apps.reports",
    "apps.pages",  # ✅ Ensure pages app is included
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # ✅ WhiteNoise must come right after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Custom middlewares
    "apps.audit.middleware.AuditLogMiddleware",
    "apps.users.middleware.JWTAuthenticationMiddleware",
]

ROOT_URLCONF = "smart_bank.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "smart_bank.wsgi.application"

# -------------------------------------
# Database (SQLite by default, PostgreSQL if DATABASE_URL is set)
# -------------------------------------
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# -------------------------------------
# Password validation
# -------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTH_USER_MODEL = "users.User"

# -------------------------------------
# Internationalization
# -------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------
# Static and Media Files (Render + Local)
# -------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # ✅ Used by collectstatic on Render
STATICFILES_DIRS = [BASE_DIR / "static"]

# ✅ WhiteNoise handles static serving in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# -------------------------------------
# REST Framework / JWT
# -------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_COOKIE": "access",
    "AUTH_COOKIE_SECURE": not DEBUG,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_SAMESITE": "Lax",
}

# -------------------------------------
# Default primary key field type
# -------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------
# API Base URL (auto-switch for local / Render)
# -------------------------------------
API_BASE_URL = env(
    "API_BASE_URL",
    default=(
        "https://modulo-bank.onrender.com/api/v1"
        if not DEBUG
        else "http://127.0.0.1:8000/api/v1"
    )
)

# -------------------------------------
# Logging (Optional - helpful for Render)
# -------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
