# Generated by Django 5.2.7 on 2025-11-04 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="tenure_months",
            new_name="term_months",
        ),
        migrations.AddField(
            model_name="loan",
            name="remaining_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="Annual interest rate in %", max_digits=5
            ),
        ),
    ]
