# Generated by Django 5.2.7 on 2025-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
