# Generated by Django 5.2.7 on 2025-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_auditlog_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
