# Generated by Django 5.2.7 on 2025-11-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_auditlog_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
