# Generated by Django 5.2.7 on 2025-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="System Notification", max_length=100),
        ),
    ]
